name: gold_app_tracker
description: "Ứng dụng theo dõi và phân tích giá vàng thế giới phục vụ tích lũy đầu tư."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.65.0

flutter:
  uses-material-design: true
  
  # Bỏ comment bên dưới nếu bạn có thư mục chứa ảnh/icon
  # assets:
  #   - assets/images/